Make Request Errors 500
hakimms/azure-sdk-for-net pull request #8
Opened 2023-08-22 21:26 UTC by hakimms

[Bug 2161532](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/2161532): Treat Only Response Validation Errors as 500

2023-08-24 21:12 UTC, HarmanDhunna commented
Please update the description with more details. For example, why is it we want response validation to be 500?

2023-08-24 21:37 UTC, HarmanDhunna requested changes

2023-08-24 21:37 UTC, HarmanDhunna commented on sdk/identity/Azure.Identity.BrokeredAuthentication/api/Azure.Identity.BrokeredAuthentication.net462.cs
> +        public bool? IsMsaPassthroughEnabled { get { throw null; } set { } }
Revert

2023-08-24 21:37 UTC, HarmanDhunna commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/Framework/AuthenticationEventMetadata.cs
> +                catch (ValidationException exception)
Comments why we are doing this.

2023-08-24 21:37 UTC, HarmanDhunna commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/Framework/AuthenticationEventMetadata.cs
> +                catch (ValidationException exception)
Why not throw `RequestValidationException` from `ValidateGraph`?

2023-08-24 21:37 UTC, HarmanDhunna commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/AuthenticationEventResponseHandler.cs
> +                        throw new RequestValidationException(AuthenticationEventResource.Ex_Missing_Request_Response);
for the catch, are there any other exception we will have other than ResponseValidationException?

2023-08-25 17:27 UTC, hakimms commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/Framework/AuthenticationEventMetadata.cs
> +                catch (ValidationException exception)
ValidateGraph is generic and validates other objects like the response as well.

2023-08-25 17:37 UTC, hakimms commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/AuthenticationEventResponseHandler.cs
> +                        throw new RequestValidationException(AuthenticationEventResource.Ex_Missing_Request_Response);
We also throw UnauthorizedAccessException if the tokens are not valid

2023-08-25 17:38 UTC, hakimms commented on sdk/identity/Azure.Identity.BrokeredAuthentication/api/Azure.Identity.BrokeredAuthentication.net462.cs
> +        public bool? IsMsaPassthroughEnabled { get { throw null; } set { } }
Done

2023-08-25 23:55 UTC, hakimms commented on sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/src/AuthenticationEventResponseHandler.cs
> +                        throw new RequestValidationException(AuthenticationEventResource.Ex_Missing_Request_Response);
We also throw an UnauthorizedAccessException if the tokens are invalid

2023-08-31 18:54 UTC, HarmanDhunna commented
Love the description. Thank you. What are you thoughts we make it a pattern of storing this kind of information in the ChangeLog.md as well. So when we go back and write documentation or how-to-guide, it's all in one place?

2023-08-31 21:30 UTC, hakimms commented
> Love the description. Thank you. What are you thoughts we make it a pattern of storing this kind of information in the ChangeLog.md as well. So when we go back and write documentation or how-to-guide, it's all in one place?

I like the idea. I will update the changelog file. Let me see how other azure sdk instances have written their changelog files

2023-09-06 19:26 UTC, merged